#!/bin/sh
#
# Generate the small set of autoconf outputs required to build n2n on macOS.
# This is useful on systems with the Xcode command line tools but no autoconf.

set -eu

SCRIPT_DIR=$(CDPATH= cd "$(dirname "$0")" && pwd)
TOPDIR=$(CDPATH= cd "$SCRIPT_DIR/.." && pwd)

cd "$TOPDIR"

SYSTEM_NAME=$(uname -s)
if [ "$SYSTEM_NAME" != "Darwin" ]; then
    echo "error: hack_fakeautoconf_macos.sh must be run on macOS" >&2
    exit 1
fi

if ! command -v clang >/dev/null 2>&1; then
    echo "error: clang was not found; install the Xcode command line tools first" >&2
    echo "       xcode-select --install" >&2
    exit 1
fi

MACHINE=$(uname -m)
CONFIG_HOST_VALUE="${MACHINE}-apple-darwin"
CONFIG_PREFIX_VALUE=${CONFIG_PREFIX:-/usr/local}
PACKAGE_VERSION_VALUE=$(scripts/version.sh)
PACKAGE_BUILDDATE_VALUE=$(scripts/version.sh date)
CC_VALUE=${CC:-clang}
AR_VALUE=${AR:-ar}
CFLAGS_VALUE=${CFLAGS:--g -O2}
LDFLAGS_VALUE=${LDFLAGS:-}
LDLIBS_EXTRA_VALUE=${LDLIBS_EXTRA:-}

cat >config.mak <<EOF
# Generated by scripts/hack_fakeautoconf_macos.sh.

CONFIG_HOST=$CONFIG_HOST_VALUE
CONFIG_HOST_OS=darwin
CONFIG_PREFIX=$CONFIG_PREFIX_VALUE

PACKAGE_VERSION=$PACKAGE_VERSION_VALUE

CC=$CC_VALUE
AR=$AR_VALUE
WINDRES=
EXE=

CFLAGS=$CFLAGS_VALUE
LDFLAGS=$LDFLAGS_VALUE
LDLIBS_EXTRA=$LDLIBS_EXTRA_VALUE
EOF

cat >include/config.h <<EOF
/* Generated by scripts/hack_fakeautoconf_macos.sh. */

#define PACKAGE_BUGREPORT ""
#define PACKAGE_BUILDDATE "$PACKAGE_BUILDDATE_VALUE"
#define PACKAGE_NAME "edge"
#define PACKAGE_STRING "edge $PACKAGE_VERSION_VALUE"
#define PACKAGE_TARNAME "edge"
#define PACKAGE_URL ""
#define PACKAGE_VERSION "$PACKAGE_VERSION_VALUE"
EOF

printf '%s\n' \
    "Created macOS build configuration" \
    "  host:     $CONFIG_HOST_VALUE" \
    "  compiler: $CC_VALUE" \
    "  version:  $PACKAGE_VERSION_VALUE" \
    "Run 'make' to build n2n."
